export default {
  login: "matheusmassari",
  id: 83505673,
  node_id: "MDQ6VXNlcjgzNTA1Njcz",
  avatar_url: "https://avatars.githubusercontent.com/u/83505673?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/matheusmassari",
  html_url: "https://github.com/matheusmassari",
  followers_url: "https://api.github.com/users/matheusmassari/followers",
  following_url:
    "https://api.github.com/users/matheusmassari/following{/other_user}",
  gists_url: "https://api.github.com/users/matheusmassari/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/matheusmassari/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/matheusmassari/subscriptions",
  organizations_url: "https://api.github.com/users/matheusmassari/orgs",
  repos_url: "https://api.github.com/users/matheusmassari/repos",
  events_url: "https://api.github.com/users/matheusmassari/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/matheusmassari/received_events",
  type: "User",
  site_admin: false,
  name: "Matheus Massari",
  company: "IEL",
  blog: "https://massari.netlify.app/",
  location: "São Luís - MA / Brazil",
  email: null,
  hireable: true,
  bio: "Web developer from Brazil, graduated in Oceanography -  always interested in new technologies and science.",
  twitter_username: null,
  public_repos: 30,
  public_gists: 1,
  followers: 9,
  following: 6,
  created_at: "2021-05-01T14:33:04Z",
  updated_at: "2022-02-05T01:35:21Z",
};